const scenarios = [
  "Corey running lights at a global dance fest.",
  "Corey starring in the hit Broadway Musical, Hamilton.",
  "Corey standing at a BBQ grill, entertaining in the back yard.",
  "Corey enjoying a sunny day.",
  "Corey rocking out on electric bass on stage at a concert.",
  "Corey flashing the boy scout salute at a camp site.",
  "Corey hiking a scenic mountain trail.",
  "Corey surfing a big wave.",
  "Corey painting a mural in a city alley.",
  "Corey piloting a small airplane.",
  "Corey teaching a cooking class.",
  "Corey exploring a foreign city.",
  "Corey building a snowman in winter.",
  "Corey conducting a symphony orchestra.",
  "Corey volunteering at a soup kitchen.",
  "Corey playing chess in a park.",
  "Corey performing a magic trick on stage.",
  "Corey sailing a boat at sunset.",
  "Corey driving a vintage car.",
  "Corey playing soccer with friends.",
  "Corey giving a TED Talk.",
  "Corey dancing salsa in a ballroom.",
  "Corey writing poetry in a café.",
  "Corey fishing by a peaceful lake.",
  "Corey attending a space launch.",
  "Corey working in a community garden.",
  "Corey riding a motorcycle on a desert road.",
  "Corey meditating in a peaceful forest.",
  "Corey photographing wildlife on a safari.",
  "Corey leading a yoga class on the beach.",
  "Corey taking part in a marathon.",
  "Corey doing stand-up comedy.",
  "Corey exploring a cave with a flashlight.",
  "Corey reading to children at a library.",
  "Corey playing a grand piano in a concert hall.",
  "Corey ice skating in a winter wonderland.",
  "Corey participating in a science fair.",
  "Corey enjoying a spa day.",
  "Corey playing beach volleyball.",
  "Corey stargazing through a telescope.",
  "Corey being a DJ at a night club.",
  "Corey flying a kite in a breezy field.",
  "Corey building sandcastles at the beach.",
  "Corey riding a horse on a country trail.",
  "Corey giving a lecture at a university.",
  "Corey enjoying a campfire with friends.",
  "Corey playing the stock market on Wall Street.",
  "Corey exploring ancient ruins.",
  "Corey giving a tour at a museum.",
  "Corey leading a protest for a cause.",
  "Corey enjoying a rollercoaster ride.",
  "Corey participating in a painting class.",
  "Corey solving a complex math equation.",
  "Corey sculpting in an art studio.",
  "Corey planting trees for a greener earth.",
  "Corey being a superhero in a comic book world.",
  "Corey hosting a game show.",
  "Corey delivering a motivational speech.",
  "Corey skydiving from a plane.",
  "Corey playing an intense game of tennis.",
  "Corey solving a mystery as a detective.",
  "Corey enjoying fine dining at a gourmet restaurant.",
  "Corey training for a triathlon.",
  "Corey playing golf on a beautiful course.",
  "Corey taking a pottery class.",
  "Corey exploring a virtual reality world.",
  "Corey performing surgery as a skilled surgeon.",
  "Corey saving lives as a firefighter.",
  "Corey arguing a case as a brilliant lawyer.",
  "Corey saving the day as a police officer.",
  "Corey designing a modern building as an architect.",
  "Corey leading a team as a successful business executive.",
  "Corey enjoying the opera in a tuxedo.",
  "Corey conducting scientific experiments in a lab.",
  "Corey enjoying a hot air balloon ride.",
  "Corey scuba diving in a coral reef.",
  "Corey attending a masquerade ball.",
  "Corey racing in a Formula 1 car.",
  "Corey enjoying a picnic in a lush park.",
  "Corey crafting in a woodworking shop.",
  "Corey jamming with a jazz band.",
  "Corey exploring the deep ocean in a submarine.",
  "Corey bungee jumping from a tall bridge.",
  "Corey enjoying a romantic date night.",
  "Corey saving animals as a veterinarian.",
  "Corey flying in a helicopter over a city.",
  "Corey dancing in a rain-soaked street.",
  "Corey solving a Rubik's Cube.",
  "Corey shopping at a bustling farmer's market.",
  "Corey enjoying a carnival ride.",
  "Corey dancing ballet on a stage.",
  "Corey engaging in a fencing duel.",
  "Corey learning a new language in a classroom.",
  "Corey exploring the galaxy as an astronaut.",
  "Corey playing cricket on a sunny day.",
  "Corey crafting jewelry in a studio.",
  "Corey attending a royal ball.",
  "Corey playing with puppies at a dog shelter.",
  "Corey riding a bicycle through a quaint village.",
  "Corey admiring a beautiful art gallery.",
  "Corey participating in a traditional tea ceremony.",
  "Corey directing a blockbuster movie.",
  "Corey learning to dance the tango.",
  "Corey enjoying a cozy winter cabin.",
  "Corey studying ancient texts as a historian.",
  "Corey walking a fashion runway as a model."
];