name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print directory structure
        run: ls -R

      - name: Update version number and Git hash
        run: |
          VERSION=$(grep -o 'alpha v[0-9.]*' ./src/App.svelte)
          NEW_VERSION_NUMBER=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          SHORT_GIT_HASH=$(echo ${GITHUB_SHA} | cut -c1-7)
          COMMIT_LINK="https://github.com/skittixch/corey-frontend/commit/$SHORT_GIT_HASH"
          NEW_VERSION_AND_LINK="alpha v$NEW_VERSION_NUMBER <a href=\"$COMMIT_LINK\">$SHORT_GIT_HASH<\/a>"
          sed -i "s|$VERSION|$NEW_VERSION_AND_LINK|g" ./src/App.svelte

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies and build
        run: |
          npm install
          npm install -g rollup
          npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "public/."
          target: "/var/www/html"

      - name: Rename folder on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rm -rf /var/www/html/corey && mv /var/www/html/public /var/www/html/corey
