name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.0

    - name: Build project
      run: |
        npm install
        npm install -g rollup
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p ~/.ssh && 
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa &&
          chmod 600 ~/.ssh/id_rsa && 
          ssh-keyscan github.com >> ~/.ssh/known_hosts && 
          cd /var/www/html/coreyDev && 
          git clone git@github.com:skittixch/corey-frontend.git && 
          cd corey-frontend && 
          git pull origin main && 
          npm install && 
          npm run build
