name: Deploy to server
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH Agent for server access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
      
    - name: Setup SSH Agent for GitHub access
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_ACTION_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa\n\tUser git" > ~/.ssh/config

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.14.0

    - name: Build project
      run: |
        npm install
        npm install -g rollup
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: "cd /var/www/html/coreyDev && git clone git@github.com:skittixch/corey-frontend.git && cd corey-frontend && git pull origin main && npm install && npm run build"
