name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and build
      run: |
        npm install
        sudo npm install -g rollup
        npm run build

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "public/."
        target: "/var/www/html/corey/public"

    - name: Move files up one directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            sudo find /var/www/html/corey -mindepth 1 -maxdepth 1 ! -name public -exec rm -rf {} \;
            sudo mv /var/www/html/corey/public/* /var/www/html/corey/ &&
            sudo rmdir /var/www/html/corey/public
      